# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

r_chilling_cpp <- function(temp, tc_min = -19.61, tc_max = 77.13, tc_opt = -0.24) {
    .Call(`_krameRcpp_r_chilling_cpp`, temp, tc_min, tc_max, tc_opt)
}

state_cpp <- function(rate, time) {
    .Call(`_krameRcpp_state_cpp`, rate, time)
}

r_forcing_cpp <- function(temp, s_chill, tf_min = 0) {
    .Call(`_krameRcpp_r_forcing_cpp`, temp, s_chill, tf_min)
}

leaf_out_status_cpp <- function(s_force) {
    .Call(`_krameRcpp_leaf_out_status_cpp`, s_force)
}

accumulated_leaf_out_cpp <- function(lo_stat) {
    .Call(`_krameRcpp_accumulated_leaf_out_cpp`, lo_stat)
}

late_frost_status_cpp <- function(accum_lo, tmin, thresh, range) {
    .Call(`_krameRcpp_late_frost_status_cpp`, accum_lo, tmin, thresh, range)
}

test_fun <- function(nums) {
    .Call(`_krameRcpp_test_fun`, nums)
}

